services:
  mysql:
    image: mysql:8.3
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "6448:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  node:
    build: .
    container_name: node_app
    working_dir: /app
    environment:
      DATABASE_URL: "mysql://root:rootpassword@mysql:3306/mydatabase"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  mysql_data: